# Скрипт проверки (шлюз isp-2)
vrrp_script chk_gateway {
    script "ping -c 1 -W 5 10.200.0.1 > /dev/null 2>&1"
    interval 5
    weight -15
}

# VI_10 - RTR-2 BACKUP
vrrp_instance VI_10 {
    state BACKUP
    interface vlan10
    virtual_router_id 10
    priority 100
    virtual_ipaddress { 172.16.10.1/24 dev vlan10 }
    track_script { chk_gateway }
}

# VI_20 - RTR-2 MASTER
vrrp_instance VI_20 {
    state MASTER
    interface vlan20
    virtual_router_id 20
    priority 115
    virtual_ipaddress { 172.16.20.1/23 dev vlan20 }
    track_script { chk_gateway }
}

# VI_30 - RTR-2 BACKUP
vrrp_instance VI_30 {
    state BACKUP
    interface vlan30
    virtual_router_id 30
    priority 100
    virtual_ipaddress { 172.16.30.1/26 dev vlan30 }
    track_script { chk_gateway }
}
